[package]
name = "silver"
version = "0.1.0"
description = "An example generated using the simple template"
authors = ["Matei Stroia <stroiamatei@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
ratatui = { version = "0.29.0", features = ["unstable-widget-ref", "unstable-rendered-line-info"] }
color-eyre = "0.6.3"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
directories-next = "2.0.0"
walkdir = "2.5.0"
mpsc = "0.2.6"
tokio = { version = "1.48.0", features = ["full"] }
futures = "0.3.31"
libc = "0.2.177"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio-stream = "0.1.17"
tokio-util = "0.7.16"
reqwest = "0.12.24"
chrono = { version = "0.4.42", features = ["serde"] }
toml = "0.9.8"
derive = { path = "./derive" }
governor = "0.10.1"
nonzero_ext = "0.3.0"
regex = "1.12.2"
async-trait = "0.1.89"
